import { existsSync, mkdirSync, writeFileSync, readFileSync, copyFileSync, unlinkSync, openSync, symlinkSync, rmSync, lstatSync } from 'fs';
import { join, dirname } from 'path';
import { execSync, spawn } from 'child_process';
import chalk from 'chalk';
import {
  WorktreeConfig,
  findProjectRoot,
  loadProjectConfig,
  getExistingWorktrees,
  getWorktreeName,
} from './config.js';

export interface DevContext {
  projectRoot: string;
  workingDir: string;
  isWorktree: boolean;
  worktreeName: string | null;
  backendPort: number;
  frontendPort: number;
}
import {
  fetchOrigin,
  createWorktree as gitCreateWorktree,
  removeWorktree as gitRemoveWorktree,
  getCurrentBranch,
  hasUncommittedChanges,
  deleteBranch,
} from './git.js';

function log(message: string): void {
  console.log(message);
}

function logSuccess(message: string): void {
  console.log(chalk.green('✓ ' + message));
}

function logWarning(message: string): void {
  console.log(chalk.yellow('⚠ ' + message));
}

function logError(message: string): void {
  console.log(chalk.red('✗ ' + message));
}

function logDim(message: string): void {
  console.log(chalk.dim(message));
}

/**
 * Add a directory to git's safe.directory config to avoid "unsafe repository" errors
 * This is needed when worktrees are created in directories owned by a different user
 */
function addToGitSafeDirectory(worktreePath: string): void {
  try {
    // Check if already in safe.directory
    const safeDirectories = execSync('git config --global --get-all safe.directory 2>/dev/null || true', {
      encoding: 'utf-8',
    }).trim().split('\n').filter(Boolean);

    if (!safeDirectories.includes(worktreePath)) {
      execSync(`git config --global --add safe.directory "${worktreePath}"`, { stdio: 'pipe' });
      logSuccess('Added worktree to git safe.directory');
    }
  } catch {
    logWarning('Could not add worktree to git safe.directory');
  }
}

export function createWorktree(config: WorktreeConfig, force: boolean = false): boolean {
  const { name, branch, baseBranch, backendPort, frontendPort, projectRoot, worktreePath, projectConfig } = config;

  // Print setup info
  console.log();
  console.log(chalk.cyan.bold('Creating Worktree'));
  console.log(chalk.dim('─'.repeat(40)));
  console.log(`  Name:          ${chalk.white(name)}`);
  console.log(`  Branch:        ${chalk.white(branch)}`);
  console.log(`  Backend Port:  ${chalk.white(backendPort.toString())}`);
  console.log(`  Frontend Port: ${chalk.white(frontendPort.toString())}`);
  console.log(`  Path:          ${chalk.white(worktreePath)}`);
  console.log();

  // Check if worktree already exists
  if (existsSync(worktreePath)) {
    if (force) {
      logWarning('Removing existing worktree...');
      gitRemoveWorktree(worktreePath, projectRoot);
    } else {
      logError(`Worktree already exists: ${worktreePath}`);
      log('Use --force to replace it, or remove it first.');
      return false;
    }
  }

  // Ensure worktrees directory exists
  const worktreesDir = dirname(worktreePath);
  if (!existsSync(worktreesDir)) {
    mkdirSync(worktreesDir, { recursive: true });
  }

  // Fetch latest
  logDim('Fetching latest from remote...');
  try {
    fetchOrigin(projectRoot);
  } catch {
    logWarning('Could not fetch from remote (continuing anyway)');
  }

  // Create worktree
  try {
    gitCreateWorktree(worktreePath, branch, baseBranch, projectRoot);
    logSuccess('Worktree created');
  } catch (error) {
    logError(`Failed to create worktree: ${error}`);
    return false;
  }

  // Add worktree to git safe.directory to avoid "unsafe repository" errors
  addToGitSafeDirectory(worktreePath);

  // Create .env file
  createEnvFile(config);

  // Copy .env.local if exists
  const envLocalSrc = join(projectRoot, '.env.local');
  const envLocalDst = join(worktreePath, '.env.local');
  if (existsSync(envLocalSrc) && !existsSync(envLocalDst)) {
    copyFileSync(envLocalSrc, envLocalDst);
    logSuccess('Copied .env.local');
  }

  // Run post-create hooks
  runPostCreateHooks(config);

  // Print success message
  printSuccessMessage(config);

  return true;
}

function createEnvFile(config: WorktreeConfig): void {
  const { name, backendPort, frontendPort, worktreePath, projectConfig } = config;

  let envContent = `# Worktree configuration for ${name}
# Auto-generated by worktree-cli

# Backend settings
API_PORT=${backendPort}

# Frontend settings
VITE_PORT=${frontendPort}

# Worktree identifier
WORKTREE_NAME=${name}
`;

  // Add database config if specified
  if (projectConfig.database) {
    const dbPattern = projectConfig.database.pattern.replace('{name}', name);
    const dbUrl = projectConfig.database.url_template.replace('{pattern}', dbPattern);
    envContent += `\n# Database\n${projectConfig.database.env_var}=${dbUrl}\n`;
  }

  // Add custom env vars
  if (projectConfig.env) {
    envContent += '\n# Project-specific settings\n';
    for (const [key, value] of Object.entries(projectConfig.env)) {
      // Fix: Remove /api suffix from VITE_API_URL if present (frontend adds /api prefix itself)
      let resolvedValue = value
        .replace('{backend_port}', String(backendPort))
        .replace('{frontend_port}', String(frontendPort))
        .replace('{name}', name);

      // Ensure VITE_API_URL doesn't have /api suffix
      if (key === 'VITE_API_URL' && resolvedValue.endsWith('/api')) {
        resolvedValue = resolvedValue.slice(0, -4);
      }

      envContent += `${key}=${resolvedValue}\n`;
    }
  }

  writeFileSync(join(worktreePath, '.env'), envContent);
  logSuccess('Environment configured (.env)');

  // Create web-app/.env for Vite (it only reads .env from its own directory)
  const webAppDir = join(worktreePath, 'web-app');
  if (existsSync(webAppDir)) {
    const webAppEnvContent = `# Frontend environment for ${name}
# Auto-generated by worktree-cli
VITE_API_URL=http://localhost:${backendPort}
`;
    writeFileSync(join(webAppDir, '.env'), webAppEnvContent);
    logSuccess('Frontend environment configured (web-app/.env)');
  }
}

function runPostCreateHooks(config: WorktreeConfig): void {
  const { worktreePath, projectConfig, projectRoot } = config;
  const isWindows = process.platform === 'win32';

  const hooks = isWindows
    ? projectConfig.hooks?.post_create_windows ?? projectConfig.hooks?.post_create
    : projectConfig.hooks?.post_create;

  if (!hooks || hooks.length === 0) return;

  logDim('Running post-create hooks...');

  let hadChmodError = false;

  for (const hook of hooks) {
    try {
      logDim(`  → ${hook}`);
      const output = execSync(hook, {
        cwd: worktreePath,
        stdio: 'pipe',
        shell: isWindows ? 'cmd.exe' : '/bin/sh',
        encoding: 'utf-8',
      });
      // Print output if any
      if (output && output.trim()) {
        console.log(output);
      }
    } catch (error: unknown) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      const errorOutput = (error as { stderr?: string })?.stderr || '';

      // Detect chmod/permission errors
      if (errorMsg.includes('chmod') || errorMsg.includes('EPERM') ||
          errorOutput.includes('chmod') || errorOutput.includes('Operation not permitted')) {
        hadChmodError = true;
        logWarning(`Hook failed (chmod error): ${hook}`);
      } else {
        logWarning(`Hook failed: ${hook}`);
      }
    }
  }

  // If chmod errors occurred, try to use symlinks as fallback
  if (hadChmodError) {
    logDim('Detected permission errors. Attempting symlink fallback...');
    trySymlinkFallback(worktreePath, projectRoot);
  }

  logSuccess('Post-create hooks completed');
}

/**
 * When chmod errors prevent venv/node_modules from being created properly,
 * fall back to symlinking from the main workspace
 */
function trySymlinkFallback(worktreePath: string, projectRoot: string): void {
  // Try to symlink venv
  const worktreeVenv = join(worktreePath, 'core-api', 'venv');
  const mainVenv = join(projectRoot, 'core-api', 'venv');

  if (existsSync(mainVenv)) {
    try {
      let shouldSymlink = false;

      if (!existsSync(worktreeVenv)) {
        // venv doesn't exist at all
        shouldSymlink = true;
      } else {
        const stat = lstatSync(worktreeVenv);
        if (stat.isSymbolicLink()) {
          // Already a symlink, skip
          shouldSymlink = false;
        } else {
          // Check if venv is broken (no activate script means it's unusable)
          const activatePath = join(worktreeVenv, 'bin', 'activate');
          const hasActivate = existsSync(activatePath);
          // If no activate script, venv is broken
          if (!hasActivate) {
            shouldSymlink = true;
          }
        }
      }

      if (shouldSymlink) {
        if (existsSync(worktreeVenv)) {
          rmSync(worktreeVenv, { recursive: true, force: true });
        }
        symlinkSync(mainVenv, worktreeVenv);
        logSuccess('Linked venv to main workspace (chmod fallback)');
      }
    } catch (error) {
      logWarning(`Could not create venv symlink fallback: ${error}`);
    }
  }

  // Try to symlink node_modules
  const worktreeNodeModules = join(worktreePath, 'web-app', 'node_modules');
  const mainNodeModules = join(projectRoot, 'web-app', 'node_modules');

  if (existsSync(mainNodeModules)) {
    try {
      let shouldSymlink = false;

      if (!existsSync(worktreeNodeModules)) {
        // node_modules doesn't exist at all
        shouldSymlink = true;
      } else {
        const stat = lstatSync(worktreeNodeModules);
        if (stat.isSymbolicLink()) {
          // Already a symlink, skip
          shouldSymlink = false;
        } else {
          // Check if node_modules is broken (no .bin)
          const binPath = join(worktreeNodeModules, '.bin');
          if (!existsSync(binPath)) {
            shouldSymlink = true;
          }
        }
      }

      if (shouldSymlink) {
        if (existsSync(worktreeNodeModules)) {
          rmSync(worktreeNodeModules, { recursive: true, force: true });
        }
        symlinkSync(mainNodeModules, worktreeNodeModules);
        logSuccess('Linked node_modules to main workspace (chmod fallback)');
      }
    } catch (error) {
      logWarning(`Could not create node_modules symlink fallback: ${error}`);
    }
  }
}

function printSuccessMessage(config: WorktreeConfig): void {
  const { name, branch, backendPort, frontendPort, worktreePath } = config;

  console.log();
  console.log(chalk.green.bold('Worktree Ready!'));
  console.log(chalk.dim('─'.repeat(40)));
  console.log(`  ${chalk.bold('Name:')}   ${name}`);
  console.log(`  ${chalk.bold('Path:')}   ${worktreePath}`);
  console.log(`  ${chalk.bold('Branch:')} ${branch}`);
  console.log();
  console.log(`  ${chalk.bold('To work in this worktree:')}`);
  console.log(chalk.cyan(`    cd ${worktreePath}`));
  console.log();
  console.log(`  ${chalk.bold('URLs:')}`);
  console.log(`    API:      http://localhost:${backendPort}`);
  console.log(`    Frontend: http://localhost:${frontendPort}`);
  console.log();
}

export function removeWorktree(
  name: string,
  options: {
    deleteBranch?: boolean;
    deleteRemote?: boolean;
    keepDatabase?: boolean;
    force?: boolean;
  } = {}
): boolean {
  const projectRoot = findProjectRoot();
  const projectConfig = loadProjectConfig(projectRoot);
  const worktreesDir = join(projectRoot, projectConfig.project.worktree_dir);
  const worktreePath = join(worktreesDir, name);

  if (!existsSync(worktreePath)) {
    logWarning(`Worktree does not exist: ${worktreePath}`);
    return true;
  }

  // Get branch name before removal
  let branchName = '';
  try {
    branchName = getCurrentBranch(worktreePath);
  } catch {
    // Ignore if we can't get branch name
  }

  console.log();
  console.log(chalk.yellow.bold('Removing Worktree'));
  console.log(chalk.dim('─'.repeat(40)));
  console.log(`  Name:   ${name}`);
  console.log(`  Branch: ${branchName || 'unknown'}`);
  console.log(`  Path:   ${worktreePath}`);
  console.log();

  // Check for uncommitted changes
  if (!options.force) {
    try {
      if (hasUncommittedChanges(worktreePath)) {
        logWarning('Worktree has uncommitted changes!');
        log('Use --force to discard changes, or commit them first.');
        return false;
      }
    } catch {
      // Ignore if we can't check status
    }
  }

  // Stop any running dev servers before removing
  const pids = readPidFile(worktreePath);
  if (pids) {
    const backendRunning = pids.backend && isProcessRunning(pids.backend);
    const frontendRunning = pids.frontend && isProcessRunning(pids.frontend);

    if (backendRunning || frontendRunning) {
      logDim('Stopping running dev servers...');
      if (pids.backend && backendRunning) {
        killProcess(pids.backend);
      }
      if (pids.frontend && frontendRunning) {
        killProcess(pids.frontend);
      }
      // Give processes time to terminate
      execSync('sleep 1', { stdio: 'ignore' });
      logSuccess('Dev servers stopped');
    }

    // Clean up PID file
    const pidFile = getPidFile(worktreePath);
    if (existsSync(pidFile)) {
      unlinkSync(pidFile);
    }
  }

  // Remove worktree
  logDim('Removing worktree...');
  gitRemoveWorktree(worktreePath, projectRoot);
  logSuccess('Worktree removed');

  // Remove database
  if (!options.keepDatabase && projectConfig.database) {
    const dbPattern = projectConfig.database.pattern.replace('{name}', name);
    const dbFile = join(projectRoot, dbPattern);
    if (existsSync(dbFile)) {
      unlinkSync(dbFile);
      logSuccess('Database removed');
    }
  }

  // Delete branch
  if (options.deleteBranch && branchName) {
    logDim(`Deleting branch: ${branchName}`);
    deleteBranch(branchName, projectRoot, options.deleteRemote);
    logSuccess('Branch deleted');
  }

  console.log();
  console.log(chalk.green.bold('Cleanup complete!'));
  return true;
}

export function listWorktrees(detailed: boolean = false): void {
  const projectRoot = findProjectRoot();
  const projectConfig = loadProjectConfig(projectRoot);
  const worktreesDir = join(projectRoot, projectConfig.project.worktree_dir);

  console.log();
  console.log(chalk.cyan.bold(`${projectConfig.project.name} Worktrees`));
  console.log(chalk.dim('─'.repeat(40)));

  const worktrees = getExistingWorktrees(projectRoot);
  let wtCount = 0;

  // Normalize paths for comparison
  const normalizedProjectRoot = projectRoot.replace(/\\/g, '/').toLowerCase();

  for (const wt of worktrees) {
    const normalizedWtPath = wt.path.replace(/\\/g, '/').toLowerCase();
    const isMain = normalizedWtPath === normalizedProjectRoot;
    const name = isMain ? null : getWorktreeName(wt.path);

    if (isMain) {
      console.log(`${chalk.bold.white('[MAIN]')} ${wt.branch || 'unknown'}`);
    } else {
      console.log(`${chalk.bold.magenta(`[${name}]`)} ${wt.branch || 'unknown'}`);
      wtCount++;
    }

    console.log(chalk.dim(`       Path: ${wt.path}`));

    if (detailed && !isMain && existsSync(wt.path)) {
      const envPath = join(wt.path, '.env');
      if (existsSync(envPath)) {
        const content = readFileSync(envPath, 'utf-8');
        const apiMatch = content.match(/API_PORT=(\d+)/);
        const viteMatch = content.match(/VITE_PORT=(\d+)/);
        if (apiMatch) console.log(chalk.dim(`       Backend:  http://localhost:${apiMatch[1]}`));
        if (viteMatch) console.log(chalk.dim(`       Frontend: http://localhost:${viteMatch[1]}`));
      }

      try {
        const hasChanges = hasUncommittedChanges(wt.path);
        if (hasChanges) {
          console.log(chalk.yellow('       Status: has uncommitted changes'));
        } else {
          console.log(chalk.dim('       Status: clean'));
        }
      } catch {
        console.log(chalk.dim('       Status: unknown'));
      }
    }

    console.log();
  }

  console.log(`${chalk.bold('Total worktrees:')} ${wtCount}`);

  if (wtCount === 0) {
    console.log();
    console.log(chalk.dim('No worktrees. Create one with:'));
    console.log(chalk.yellow('  worktree create'));
  }
}

export function cleanupAll(force: boolean = false, keepDatabases: boolean = false): void {
  const projectRoot = findProjectRoot();
  const projectConfig = loadProjectConfig(projectRoot);
  const worktreesDir = join(projectRoot, projectConfig.project.worktree_dir);

  const worktrees = getExistingWorktrees(projectRoot);
  let removed = 0;

  // Normalize paths for comparison
  const normalizedProjectRoot = projectRoot.replace(/\\/g, '/').toLowerCase();
  const normalizedWorktreesDir = worktreesDir.replace(/\\/g, '/').toLowerCase();

  for (const wt of worktrees) {
    const normalizedWtPath = wt.path.replace(/\\/g, '/').toLowerCase();

    // Skip main worktree
    if (normalizedWtPath === normalizedProjectRoot) continue;

    // Check if it's in our worktrees directory
    if (normalizedWtPath.startsWith(normalizedWorktreesDir)) {
      const name = getWorktreeName(wt.path);
      logDim(`Removing ${name}...`);
      removeWorktree(name, { force, keepDatabase: keepDatabases });
      removed++;
    }
  }

  if (removed === 0) {
    logWarning('No worktrees to clean up.');
  } else {
    console.log();
    console.log(chalk.green.bold(`Cleaned up ${removed} worktree(s).`));
  }
}

/**
 * Find the real project root (handles being inside a worktree)
 */
function findRealProjectRoot(): { projectRoot: string; isInWorktree: boolean; worktreeName: string | null } {
  const cwd = process.cwd();

  // Check if current directory has a .env with WORKTREE_NAME (most reliable worktree detection)
  const cwdEnvPath = join(cwd, '.env');
  if (existsSync(cwdEnvPath)) {
    const content = readFileSync(cwdEnvPath, 'utf-8');
    const worktreeMatch = content.match(/WORKTREE_NAME=(.+)/);
    if (worktreeMatch) {
      // We're in a worktree - find the main project root
      // Worktrees are typically in <project>/.worktrees/<name>
      const worktreeName = worktreeMatch[1].trim();

      // Walk up to find the real project root (the one with worktree.toml)
      let current = dirname(cwd); // Go up from worktree dir
      while (current !== dirname(current)) {
        if (existsSync(join(current, 'worktree.toml'))) {
          return { projectRoot: current, isInWorktree: true, worktreeName };
        }
        current = dirname(current);
      }

      // Fallback: assume we're two levels deep (.worktrees/wt-xxxx)
      const assumedRoot = dirname(dirname(cwd));
      return { projectRoot: assumedRoot, isInWorktree: true, worktreeName };
    }
  }

  // Not in a worktree - find project root normally
  return { projectRoot: findProjectRoot(), isInWorktree: false, worktreeName: null };
}

/**
 * Detect the current development context (main project or worktree)
 */
export function getDevContext(worktreeName?: string): DevContext {
  const { projectRoot, isInWorktree, worktreeName: detectedWorktreeName } = findRealProjectRoot();
  const projectConfig = loadProjectConfig(projectRoot);
  const cwd = process.cwd();

  // If a worktree name is specified, use that
  if (worktreeName) {
    const worktreePath = join(projectRoot, projectConfig.project.worktree_dir, worktreeName);
    const envPath = join(worktreePath, '.env');

    if (!existsSync(worktreePath)) {
      throw new Error(`Worktree '${worktreeName}' not found`);
    }

    const { backendPort, frontendPort } = readPortsFromEnv(envPath, projectConfig);

    return {
      projectRoot,
      workingDir: worktreePath,
      isWorktree: true,
      worktreeName,
      backendPort,
      frontendPort,
    };
  }

  // If we detected we're in a worktree via .env
  if (isInWorktree && detectedWorktreeName) {
    const worktreePath = join(projectRoot, projectConfig.project.worktree_dir, detectedWorktreeName);
    const envPath = join(worktreePath, '.env');
    const { backendPort, frontendPort } = readPortsFromEnv(envPath, projectConfig);

    return {
      projectRoot,
      workingDir: worktreePath,
      isWorktree: true,
      worktreeName: detectedWorktreeName,
      backendPort,
      frontendPort,
    };
  }

  // Check if we're inside a worktree by path
  const worktreesDir = join(projectRoot, projectConfig.project.worktree_dir);
  const normalizedCwd = cwd.replace(/\\/g, '/').toLowerCase();
  const normalizedWorktreesDir = worktreesDir.replace(/\\/g, '/').toLowerCase();

  if (normalizedCwd.startsWith(normalizedWorktreesDir)) {
    // We're inside a worktree - extract name from path
    const relativePath = cwd.slice(worktreesDir.length + 1);
    const name = relativePath.split(/[/\\]/)[0];
    const worktreePath = join(worktreesDir, name);
    const envPath = join(worktreePath, '.env');

    const { backendPort, frontendPort } = readPortsFromEnv(envPath, projectConfig);

    return {
      projectRoot,
      workingDir: worktreePath,
      isWorktree: true,
      worktreeName: name,
      backendPort,
      frontendPort,
    };
  }

  // We're in the main project
  return {
    projectRoot,
    workingDir: projectRoot,
    isWorktree: false,
    worktreeName: null,
    backendPort: projectConfig.ports.backend_base,
    frontendPort: projectConfig.ports.frontend_base,
  };
}

function readPortsFromEnv(
  envPath: string,
  projectConfig: ReturnType<typeof loadProjectConfig>
): { backendPort: number; frontendPort: number } {
  let backendPort = projectConfig.ports.backend_base;
  let frontendPort = projectConfig.ports.frontend_base;

  if (existsSync(envPath)) {
    const content = readFileSync(envPath, 'utf-8');
    const apiMatch = content.match(/API_PORT=(\d+)/);
    const viteMatch = content.match(/VITE_PORT=(\d+)/);
    if (apiMatch) backendPort = parseInt(apiMatch[1], 10);
    if (viteMatch) frontendPort = parseInt(viteMatch[1], 10);
  }

  return { backendPort, frontendPort };
}

interface PidFile {
  backend?: number;
  frontend?: number;
  startedAt: string;
  context: string;
  backendPort: number;
  frontendPort: number;
}

function getLogsDir(workingDir: string): string {
  return join(workingDir, '.dev-logs');
}

function getPidFile(workingDir: string): string {
  return join(getLogsDir(workingDir), 'pids.json');
}

function readPidFile(workingDir: string): PidFile | null {
  const pidFile = getPidFile(workingDir);
  if (existsSync(pidFile)) {
    try {
      return JSON.parse(readFileSync(pidFile, 'utf-8'));
    } catch {
      return null;
    }
  }
  return null;
}

function writePidFile(workingDir: string, data: PidFile): void {
  const logsDir = getLogsDir(workingDir);
  if (!existsSync(logsDir)) {
    mkdirSync(logsDir, { recursive: true });
  }
  writeFileSync(getPidFile(workingDir), JSON.stringify(data, null, 2));
}

function isProcessRunning(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

function killProcess(pid: number): boolean {
  const isWindows = process.platform === 'win32';

  try {
    if (isWindows) {
      // On Windows, use taskkill to kill the process tree
      execSync(`taskkill /PID ${pid} /T /F`, { stdio: 'pipe' });
    } else {
      // On Unix, kill the entire process group by using negative PID
      // The process was spawned with detached: true, making it a process group leader
      try {
        process.kill(-pid, 'SIGTERM');
      } catch {
        // Fallback to killing just the PID if group kill fails
        process.kill(pid, 'SIGTERM');
      }
    }
    return true;
  } catch {
    return false;
  }
}

/**
 * Ensure web-app/.env exists with correct VITE_API_URL
 */
function ensureFrontendEnv(workingDir: string, backendPort: number): void {
  const webAppEnvPath = join(workingDir, 'web-app', '.env');
  const expectedUrl = `VITE_API_URL=http://localhost:${backendPort}`;

  if (existsSync(webAppEnvPath)) {
    // Check if VITE_API_URL is correct (no /api suffix)
    const content = readFileSync(webAppEnvPath, 'utf-8');
    if (content.includes(`VITE_API_URL=http://localhost:${backendPort}/api`)) {
      // Fix incorrect URL with /api suffix
      const fixedContent = content.replace(
        /VITE_API_URL=http:\/\/localhost:\d+\/api/,
        expectedUrl
      );
      writeFileSync(webAppEnvPath, fixedContent);
      logSuccess('Fixed web-app/.env (removed /api suffix from VITE_API_URL)');
    } else if (!content.includes('VITE_API_URL=')) {
      // Add VITE_API_URL if missing
      writeFileSync(webAppEnvPath, content + `\n${expectedUrl}\n`);
      logSuccess('Added VITE_API_URL to web-app/.env');
    }
  } else {
    // Create web-app/.env
    writeFileSync(webAppEnvPath, `${expectedUrl}\n`);
    logSuccess('Created web-app/.env with VITE_API_URL');
  }
}

/**
 * Check if database exists and is initialized
 */
function checkDatabase(workingDir: string, worktreeName: string | null): boolean {
  const dbName = worktreeName ? `financial_analysis_${worktreeName}.db` : 'financial_analysis.db';
  // Database is stored in core-api directory
  const dbPath = join(workingDir, 'core-api', dbName);
  return existsSync(dbPath);
}

/**
 * Initialize the database for a worktree
 */
function initializeDatabase(workingDir: string): boolean {
  const isWindows = process.platform === 'win32';
  const coreApiDir = join(workingDir, 'core-api');

  logDim('Initializing database...');

  try {
    execSync(
      isWindows
        ? `cd /d "${coreApiDir}" && ..\\venv\\Scripts\\activate && python -m src.financial_analysis.database.init_db`
        : `cd "${coreApiDir}" && source ../venv/bin/activate 2>/dev/null || source venv/bin/activate && python -m src.financial_analysis.database.init_db`,
      {
        cwd: workingDir,
        stdio: 'pipe',
        shell: isWindows ? 'cmd.exe' : '/bin/bash',
      }
    );
    logSuccess('Database initialized');
    return true;
  } catch (error) {
    logError(`Failed to initialize database: ${error}`);
    return false;
  }
}

/**
 * Start development servers (backend + frontend) as background processes
 */
export function startDev(worktreeName?: string): boolean {
  const context = getDevContext(worktreeName);
  const isWindows = process.platform === 'win32';
  const logsDir = getLogsDir(context.workingDir);

  console.log();
  console.log(chalk.cyan.bold('Starting Development Servers'));
  console.log(chalk.dim('─'.repeat(40)));
  console.log(`  ${chalk.bold('Context:')}  ${context.isWorktree ? chalk.magenta(`[${context.worktreeName}]`) : chalk.white('[MAIN]')}`);
  console.log(`  ${chalk.bold('Path:')}     ${context.workingDir}`);
  console.log(`  ${chalk.bold('Backend:')}  http://localhost:${context.backendPort}`);
  console.log(`  ${chalk.bold('Frontend:')} http://localhost:${context.frontendPort}`);
  console.log();

  // Check if servers are already running
  const existingPids = readPidFile(context.workingDir);
  if (existingPids) {
    const backendRunning = existingPids.backend && isProcessRunning(existingPids.backend);
    const frontendRunning = existingPids.frontend && isProcessRunning(existingPids.frontend);

    if (backendRunning || frontendRunning) {
      logWarning('Servers appear to be already running:');
      if (backendRunning) log(`  Backend PID: ${existingPids.backend}`);
      if (frontendRunning) log(`  Frontend PID: ${existingPids.frontend}`);
      console.log();
      log('Run ' + chalk.cyan('worktree dev --stop') + ' first to stop them.');
      return false;
    } else {
      // PIDs exist but processes aren't running - clean up stale PID file
      logDim('Cleaning up stale PID file...');
      const pidFile = getPidFile(context.workingDir);
      if (existsSync(pidFile)) {
        unlinkSync(pidFile);
      }
    }
  }

  // Ensure web-app/.env exists with correct VITE_API_URL
  ensureFrontendEnv(context.workingDir, context.backendPort);

  // Check and initialize database if needed
  if (!checkDatabase(context.workingDir, context.worktreeName)) {
    log('Database not found. Initializing...');
    if (!initializeDatabase(context.workingDir)) {
      logWarning('Database initialization failed. Server may not work correctly.');
    }
  }

  // Create logs directory
  if (!existsSync(logsDir)) {
    mkdirSync(logsDir, { recursive: true });
  }

  // Create log files
  const backendLogPath = join(logsDir, 'backend.log');
  const frontendLogPath = join(logsDir, 'frontend.log');

  const backendLog = openSync(backendLogPath, 'w');
  const frontendLog = openSync(frontendLogPath, 'w');

  logDim('Starting backend server...');

  // Start backend
  const backendProcess = spawn(
    isWindows ? 'cmd' : 'bash',
    isWindows
      ? ['/c', `cd /d "${join(context.workingDir, 'core-api')}" && ..\\venv\\Scripts\\activate && python -m uvicorn src.financial_analysis.api.main:app --reload --host 0.0.0.0 --port ${context.backendPort}`]
      : ['-c', `cd "${join(context.workingDir, 'core-api')}" && source ../venv/bin/activate 2>/dev/null || source venv/bin/activate && python -m uvicorn src.financial_analysis.api.main:app --reload --host 0.0.0.0 --port ${context.backendPort}`],
    {
      detached: true,
      stdio: ['ignore', backendLog, backendLog],
      cwd: context.workingDir,
    }
  );
  backendProcess.unref();

  logDim('Starting frontend server...');

  // Start frontend
  const frontendProcess = spawn(
    isWindows ? 'cmd' : 'bash',
    isWindows
      ? ['/c', `cd /d "${join(context.workingDir, 'web-app')}" && npm run dev -- --host --port ${context.frontendPort}`]
      : ['-c', `cd "${join(context.workingDir, 'web-app')}" && npm run dev -- --host --port ${context.frontendPort}`],
    {
      detached: true,
      stdio: ['ignore', frontendLog, frontendLog],
      cwd: context.workingDir,
    }
  );
  frontendProcess.unref();

  // Save PIDs
  writePidFile(context.workingDir, {
    backend: backendProcess.pid,
    frontend: frontendProcess.pid,
    startedAt: new Date().toISOString(),
    context: context.isWorktree ? context.worktreeName! : 'main',
    backendPort: context.backendPort,
    frontendPort: context.frontendPort,
  });

  console.log();
  logSuccess('Servers started in background!');
  console.log();
  console.log(chalk.bold('Server URLs:'));
  console.log(`  ${chalk.green('API Docs:')}  http://localhost:${context.backendPort}/api/docs`);
  console.log(`  ${chalk.green('Frontend:')} http://localhost:${context.frontendPort}`);
  console.log();
  console.log(chalk.bold('Logs:'));
  console.log(`  ${chalk.dim('Backend:')}  ${backendLogPath}`);
  console.log(`  ${chalk.dim('Frontend:')} ${frontendLogPath}`);
  console.log();
  console.log(chalk.bold('Commands:'));
  console.log(`  ${chalk.cyan('worktree dev --stop')}   Stop the servers`);
  console.log(`  ${chalk.cyan('worktree dev --logs')}   Tail the log files`);
  console.log(`  ${chalk.cyan('worktree dev --status')} Check server status`);
  console.log();

  return true;
}

/**
 * Stop running development servers
 */
export function stopDev(worktreeName?: string): boolean {
  const context = getDevContext(worktreeName);
  const pids = readPidFile(context.workingDir);

  console.log();
  console.log(chalk.yellow.bold('Stopping Development Servers'));
  console.log(chalk.dim('─'.repeat(40)));

  if (!pids) {
    logWarning('No running servers found (no PID file)');
    return true;
  }

  let stopped = 0;

  if (pids.backend) {
    if (isProcessRunning(pids.backend)) {
      logDim(`Stopping backend (PID ${pids.backend})...`);
      if (killProcess(pids.backend)) {
        logSuccess('Backend stopped');
        stopped++;
      } else {
        logError(`Failed to stop backend (PID ${pids.backend})`);
      }
    } else {
      logDim('Backend was not running');
    }
  }

  if (pids.frontend) {
    if (isProcessRunning(pids.frontend)) {
      logDim(`Stopping frontend (PID ${pids.frontend})...`);
      if (killProcess(pids.frontend)) {
        logSuccess('Frontend stopped');
        stopped++;
      } else {
        logError(`Failed to stop frontend (PID ${pids.frontend})`);
      }
    } else {
      logDim('Frontend was not running');
    }
  }

  // Clean up PID file
  const pidFile = getPidFile(context.workingDir);
  if (existsSync(pidFile)) {
    unlinkSync(pidFile);
  }

  console.log();
  if (stopped > 0) {
    logSuccess(`Stopped ${stopped} server(s)`);
  } else {
    log('No servers were running');
  }
  console.log();

  return true;
}

/**
 * Show status of development servers
 */
export function statusDev(worktreeName?: string): void {
  const context = getDevContext(worktreeName);
  const pids = readPidFile(context.workingDir);

  console.log();
  console.log(chalk.cyan.bold('Development Server Status'));
  console.log(chalk.dim('─'.repeat(40)));
  console.log(`  ${chalk.bold('Context:')} ${context.isWorktree ? chalk.magenta(`[${context.worktreeName}]`) : chalk.white('[MAIN]')}`);
  console.log(`  ${chalk.bold('Path:')}    ${context.workingDir}`);
  console.log();

  if (!pids) {
    log('No servers configured (no PID file found)');
    console.log();
    log(`Run ${chalk.cyan('worktree dev')} to start servers.`);
    console.log();
    return;
  }

  console.log(`  ${chalk.bold('Started:')} ${pids.startedAt}`);
  console.log();

  const backendRunning = pids.backend && isProcessRunning(pids.backend);
  const frontendRunning = pids.frontend && isProcessRunning(pids.frontend);

  console.log(chalk.bold('Backend:'));
  console.log(`  Status: ${backendRunning ? chalk.green('● Running') : chalk.red('○ Stopped')}`);
  console.log(`  PID:    ${pids.backend || 'N/A'}`);
  console.log(`  URL:    http://localhost:${pids.backendPort}/api/docs`);
  console.log();

  console.log(chalk.bold('Frontend:'));
  console.log(`  Status: ${frontendRunning ? chalk.green('● Running') : chalk.red('○ Stopped')}`);
  console.log(`  PID:    ${pids.frontend || 'N/A'}`);
  console.log(`  URL:    http://localhost:${pids.frontendPort}`);
  console.log();
}

/**
 * Tail the development server logs
 */
export function logsDev(worktreeName?: string): void {
  const context = getDevContext(worktreeName);
  const logsDir = getLogsDir(context.workingDir);
  const backendLogPath = join(logsDir, 'backend.log');
  const frontendLogPath = join(logsDir, 'frontend.log');

  console.log();
  console.log(chalk.cyan.bold('Development Server Logs'));
  console.log(chalk.dim('─'.repeat(40)));

  if (!existsSync(logsDir)) {
    logWarning('No logs directory found. Start servers first with: worktree dev');
    return;
  }

  console.log(`  ${chalk.bold('Backend log:')}  ${backendLogPath}`);
  console.log(`  ${chalk.bold('Frontend log:')} ${frontendLogPath}`);
  console.log();
  console.log(chalk.dim('Tailing logs (Ctrl+C to stop)...'));
  console.log(chalk.dim('─'.repeat(40)));
  console.log();

  // Use tail to follow both log files
  const isWindows = process.platform === 'win32';

  try {
    if (isWindows) {
      // On Windows, use PowerShell Get-Content -Wait
      execSync(
        `powershell -Command "Get-Content -Path '${backendLogPath}','${frontendLogPath}' -Wait"`,
        { stdio: 'inherit' }
      );
    } else {
      // On Unix, use tail -f
      execSync(`tail -f "${backendLogPath}" "${frontendLogPath}"`, { stdio: 'inherit' });
    }
  } catch {
    // User pressed Ctrl+C
    console.log();
    log('Stopped tailing logs.');
  }
}
