import { existsSync, mkdirSync, writeFileSync, readFileSync, copyFileSync, unlinkSync } from 'fs';
import { join, dirname } from 'path';
import { execSync } from 'child_process';
import chalk from 'chalk';
import {
  WorktreeConfig,
  findProjectRoot,
  loadProjectConfig,
  getExistingWorktrees,
  getWorktreeName,
} from './config.js';
import {
  fetchOrigin,
  createWorktree as gitCreateWorktree,
  removeWorktree as gitRemoveWorktree,
  getCurrentBranch,
  hasUncommittedChanges,
  deleteBranch,
} from './git.js';

function log(message: string): void {
  console.log(message);
}

function logSuccess(message: string): void {
  console.log(chalk.green('✓ ' + message));
}

function logWarning(message: string): void {
  console.log(chalk.yellow('⚠ ' + message));
}

function logError(message: string): void {
  console.log(chalk.red('✗ ' + message));
}

function logDim(message: string): void {
  console.log(chalk.dim(message));
}

export function createWorktree(config: WorktreeConfig, force: boolean = false): boolean {
  const { name, branch, baseBranch, backendPort, frontendPort, projectRoot, worktreePath, projectConfig } = config;

  // Print setup info
  console.log();
  console.log(chalk.cyan.bold('Creating Worktree'));
  console.log(chalk.dim('─'.repeat(40)));
  console.log(`  Name:          ${chalk.white(name)}`);
  console.log(`  Branch:        ${chalk.white(branch)}`);
  console.log(`  Backend Port:  ${chalk.white(backendPort.toString())}`);
  console.log(`  Frontend Port: ${chalk.white(frontendPort.toString())}`);
  console.log(`  Path:          ${chalk.white(worktreePath)}`);
  console.log();

  // Check if worktree already exists
  if (existsSync(worktreePath)) {
    if (force) {
      logWarning('Removing existing worktree...');
      gitRemoveWorktree(worktreePath, projectRoot);
    } else {
      logError(`Worktree already exists: ${worktreePath}`);
      log('Use --force to replace it, or remove it first.');
      return false;
    }
  }

  // Ensure worktrees directory exists
  const worktreesDir = dirname(worktreePath);
  if (!existsSync(worktreesDir)) {
    mkdirSync(worktreesDir, { recursive: true });
  }

  // Fetch latest
  logDim('Fetching latest from remote...');
  try {
    fetchOrigin(projectRoot);
  } catch {
    logWarning('Could not fetch from remote (continuing anyway)');
  }

  // Create worktree
  try {
    gitCreateWorktree(worktreePath, branch, baseBranch, projectRoot);
    logSuccess('Worktree created');
  } catch (error) {
    logError(`Failed to create worktree: ${error}`);
    return false;
  }

  // Create .env file
  createEnvFile(config);

  // Copy .env.local if exists
  const envLocalSrc = join(projectRoot, '.env.local');
  const envLocalDst = join(worktreePath, '.env.local');
  if (existsSync(envLocalSrc) && !existsSync(envLocalDst)) {
    copyFileSync(envLocalSrc, envLocalDst);
    logSuccess('Copied .env.local');
  }

  // Run post-create hooks
  runPostCreateHooks(config);

  // Print success message
  printSuccessMessage(config);

  return true;
}

function createEnvFile(config: WorktreeConfig): void {
  const { name, backendPort, frontendPort, worktreePath, projectConfig } = config;

  let envContent = `# Worktree configuration for ${name}
# Auto-generated by worktree-cli

# Backend settings
API_PORT=${backendPort}

# Frontend settings
VITE_PORT=${frontendPort}

# Worktree identifier
WORKTREE_NAME=${name}
`;

  // Add database config if specified
  if (projectConfig.database) {
    const dbPattern = projectConfig.database.pattern.replace('{name}', name);
    const dbUrl = projectConfig.database.url_template.replace('{pattern}', dbPattern);
    envContent += `\n# Database\n${projectConfig.database.env_var}=${dbUrl}\n`;
  }

  // Add custom env vars
  if (projectConfig.env) {
    envContent += '\n# Project-specific settings\n';
    for (const [key, value] of Object.entries(projectConfig.env)) {
      const resolvedValue = value
        .replace('{backend_port}', String(backendPort))
        .replace('{frontend_port}', String(frontendPort))
        .replace('{name}', name);
      envContent += `${key}=${resolvedValue}\n`;
    }
  }

  writeFileSync(join(worktreePath, '.env'), envContent);
  logSuccess('Environment configured (.env)');
}

function runPostCreateHooks(config: WorktreeConfig): void {
  const { worktreePath, projectConfig } = config;
  const isWindows = process.platform === 'win32';

  const hooks = isWindows
    ? projectConfig.hooks?.post_create_windows ?? projectConfig.hooks?.post_create
    : projectConfig.hooks?.post_create;

  if (!hooks || hooks.length === 0) return;

  logDim('Running post-create hooks...');

  for (const hook of hooks) {
    try {
      logDim(`  → ${hook}`);
      execSync(hook, {
        cwd: worktreePath,
        stdio: 'inherit',
        shell: isWindows ? 'cmd.exe' : '/bin/sh',
      });
    } catch (error) {
      logWarning(`Hook failed: ${hook}`);
    }
  }

  logSuccess('Post-create hooks completed');
}

function printSuccessMessage(config: WorktreeConfig): void {
  const { name, branch, backendPort, frontendPort, worktreePath } = config;

  console.log();
  console.log(chalk.green.bold('Worktree Ready!'));
  console.log(chalk.dim('─'.repeat(40)));
  console.log(`  ${chalk.bold('Name:')}   ${name}`);
  console.log(`  ${chalk.bold('Path:')}   ${worktreePath}`);
  console.log(`  ${chalk.bold('Branch:')} ${branch}`);
  console.log();
  console.log(`  ${chalk.bold('To work in this worktree:')}`);
  console.log(chalk.cyan(`    cd ${worktreePath}`));
  console.log();
  console.log(`  ${chalk.bold('URLs:')}`);
  console.log(`    API:      http://localhost:${backendPort}`);
  console.log(`    Frontend: http://localhost:${frontendPort}`);
  console.log();
}

export function removeWorktree(
  name: string,
  options: {
    deleteBranch?: boolean;
    deleteRemote?: boolean;
    keepDatabase?: boolean;
    force?: boolean;
  } = {}
): boolean {
  const projectRoot = findProjectRoot();
  const projectConfig = loadProjectConfig(projectRoot);
  const worktreesDir = join(projectRoot, projectConfig.project.worktree_dir);
  const worktreePath = join(worktreesDir, name);

  if (!existsSync(worktreePath)) {
    logWarning(`Worktree does not exist: ${worktreePath}`);
    return true;
  }

  // Get branch name before removal
  let branchName = '';
  try {
    branchName = getCurrentBranch(worktreePath);
  } catch {
    // Ignore if we can't get branch name
  }

  console.log();
  console.log(chalk.yellow.bold('Removing Worktree'));
  console.log(chalk.dim('─'.repeat(40)));
  console.log(`  Name:   ${name}`);
  console.log(`  Branch: ${branchName || 'unknown'}`);
  console.log(`  Path:   ${worktreePath}`);
  console.log();

  // Check for uncommitted changes
  if (!options.force) {
    try {
      if (hasUncommittedChanges(worktreePath)) {
        logWarning('Worktree has uncommitted changes!');
        log('Use --force to discard changes, or commit them first.');
        return false;
      }
    } catch {
      // Ignore if we can't check status
    }
  }

  // Remove worktree
  logDim('Removing worktree...');
  gitRemoveWorktree(worktreePath, projectRoot);
  logSuccess('Worktree removed');

  // Remove database
  if (!options.keepDatabase && projectConfig.database) {
    const dbPattern = projectConfig.database.pattern.replace('{name}', name);
    const dbFile = join(projectRoot, dbPattern);
    if (existsSync(dbFile)) {
      unlinkSync(dbFile);
      logSuccess('Database removed');
    }
  }

  // Delete branch
  if (options.deleteBranch && branchName) {
    logDim(`Deleting branch: ${branchName}`);
    deleteBranch(branchName, projectRoot, options.deleteRemote);
    logSuccess('Branch deleted');
  }

  console.log();
  console.log(chalk.green.bold('Cleanup complete!'));
  return true;
}

export function listWorktrees(detailed: boolean = false): void {
  const projectRoot = findProjectRoot();
  const projectConfig = loadProjectConfig(projectRoot);
  const worktreesDir = join(projectRoot, projectConfig.project.worktree_dir);

  console.log();
  console.log(chalk.cyan.bold(`${projectConfig.project.name} Worktrees`));
  console.log(chalk.dim('─'.repeat(40)));

  const worktrees = getExistingWorktrees(projectRoot);
  let wtCount = 0;

  // Normalize paths for comparison
  const normalizedProjectRoot = projectRoot.replace(/\\/g, '/').toLowerCase();

  for (const wt of worktrees) {
    const normalizedWtPath = wt.path.replace(/\\/g, '/').toLowerCase();
    const isMain = normalizedWtPath === normalizedProjectRoot;
    const name = isMain ? null : getWorktreeName(wt.path);

    if (isMain) {
      console.log(`${chalk.bold.white('[MAIN]')} ${wt.branch || 'unknown'}`);
    } else {
      console.log(`${chalk.bold.magenta(`[${name}]`)} ${wt.branch || 'unknown'}`);
      wtCount++;
    }

    console.log(chalk.dim(`       Path: ${wt.path}`));

    if (detailed && !isMain && existsSync(wt.path)) {
      const envPath = join(wt.path, '.env');
      if (existsSync(envPath)) {
        const content = readFileSync(envPath, 'utf-8');
        const apiMatch = content.match(/API_PORT=(\d+)/);
        const viteMatch = content.match(/VITE_PORT=(\d+)/);
        if (apiMatch) console.log(chalk.dim(`       Backend:  http://localhost:${apiMatch[1]}`));
        if (viteMatch) console.log(chalk.dim(`       Frontend: http://localhost:${viteMatch[1]}`));
      }

      try {
        const hasChanges = hasUncommittedChanges(wt.path);
        if (hasChanges) {
          console.log(chalk.yellow('       Status: has uncommitted changes'));
        } else {
          console.log(chalk.dim('       Status: clean'));
        }
      } catch {
        console.log(chalk.dim('       Status: unknown'));
      }
    }

    console.log();
  }

  console.log(`${chalk.bold('Total worktrees:')} ${wtCount}`);

  if (wtCount === 0) {
    console.log();
    console.log(chalk.dim('No worktrees. Create one with:'));
    console.log(chalk.yellow('  worktree create'));
  }
}

export function cleanupAll(force: boolean = false, keepDatabases: boolean = false): void {
  const projectRoot = findProjectRoot();
  const projectConfig = loadProjectConfig(projectRoot);
  const worktreesDir = join(projectRoot, projectConfig.project.worktree_dir);

  const worktrees = getExistingWorktrees(projectRoot);
  let removed = 0;

  // Normalize paths for comparison
  const normalizedProjectRoot = projectRoot.replace(/\\/g, '/').toLowerCase();
  const normalizedWorktreesDir = worktreesDir.replace(/\\/g, '/').toLowerCase();

  for (const wt of worktrees) {
    const normalizedWtPath = wt.path.replace(/\\/g, '/').toLowerCase();

    // Skip main worktree
    if (normalizedWtPath === normalizedProjectRoot) continue;

    // Check if it's in our worktrees directory
    if (normalizedWtPath.startsWith(normalizedWorktreesDir)) {
      const name = getWorktreeName(wt.path);
      logDim(`Removing ${name}...`);
      removeWorktree(name, { force, keepDatabase: keepDatabases });
      removed++;
    }
  }

  if (removed === 0) {
    logWarning('No worktrees to clean up.');
  } else {
    console.log();
    console.log(chalk.green.bold(`Cleaned up ${removed} worktree(s).`));
  }
}
